### ISSUE TITLE
canMakePayment

### ISSUE THREAD

**Issue by gauntface** [madmath/payment-request-show#12]
Print the error message when the method rejects.

**Comment by biseraivanovska** [comment]
How can a method get rejected?

**Comment by gauntface** [comment]
Can make payment has a quota meaning calling it too frequently will reject the promise.

**Comment by biseraivanovska** [comment]
that's true, and i think it's okay.

I am more interested in : what makes a payment method identifier a valid one? https://www.w3.org/TR/payment-method-id/#dfn-url-based-payment-method-identifier here the valid definition is okay, but still, calling the payment method first time, it can be rejected. Is it because the corresponding app is not recognized by the package manager?

**Comment by madmath** [comment]
Closed through [this pull request](https://github.com/madmath/payment-request-show/pull/18)
